### ISSUE TITLE
Uncaught ReferenceError: Diont is not defined

### ISSUE THREAD

**Issue by darkwolfjack** [willemmulder/Diont-for-Cordova#6]
I'm using Diont for Cordova with Ionic. When debugging on Android device I got the error 'Uncaught ReferenceError: Diont is not defined'.

**Comment by willemmulder** [comment]
Hey @darkwolfjack, nice using the two together! What are you working on?

The error message that you get is due to the fact that the plugin (somehow) was not properly loaded. How did you install Diont for Cordova?

**Comment by darkwolfjack** [comment]
Thanks @willemmulder, I followed the Readme instructions to install Diont for Cordova. And when using 'Cordova plugin ls' Diont was listed as installed plugin.

**Comment by darkwolfjack** [comment]
@willemmulder Sorry, I figured it out. The reason Diont was not loaded was because I put it in an Angular service and instantiate the service within the deviceready() event listener. So before deviceready() the plugins were not loaded completely.

**Comment by willemmulder** [comment]
Great you solved it!
