### ISSUE TITLE
wifi strength program

### ISSUE THREAD

**Issue by AElkenawy** [willemmulder/Diont-for-Cordova#8]
Hello 
I need to make a program to measure special wifi MAC addresses strength with my mobile phone , but i am totally beginner to javascript and i don't know where to start so what are steps ?? so if anyone have an already-made example this would be awesome :) 

I also used construct 2 (Game engine compatible with cordova .. etc) to make such programs , but i can't find a plugin for it and don't know (if possible) how to convert the src , www , .... files to the C2 files , so if anyone know about that would be great.
Thanks in advance

**Comment by willemmulder** [comment]
Hi @Amorasamy this Cordova plugin does not help you in measuring wifi strength, it is meant to provide to do service-discovery which is a totally different thing. 

I'd suggest start googling around the topics that you're dealing with, but be prepared to go deep; the topics at hand can be quite complex for a beginner. Still, please, PLEASE don't start copy-pasting some code examples and hope it works, but try to actually understand what's going on... Good luck!
